spring:
  application:
    name: chins-mall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            ## 如果带了参数url，且参数值是baidu
            - Query=url, baidu
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url, qq

        ## 商品服务
        - id: product_route
          uri: lb://chins-mall-product
          predicates:
            - Path=/api/product/**
          filters:
            ## /api/product/category/list/tree -> /product/category/list/tree
            - RewritePath=/api/(?<segment>.*), /$\{segment}


server:
  port: 8088
